<?php
define('WP_INSTALLING',true);
require getenv('ORBIT_WP_CORE').'/wp-load.php';
require_once ABSPATH.'wp-admin/includes/upgrade.php';
if(!is_blog_installed())wp_install('Orbit integration fixture','fixture_admin','fixture@example.test',true,'',bin2hex(random_bytes(24)));
$checks=0;
function verify_runtime($condition,$label){global $checks;if(!$condition)throw new RuntimeException($label);$checks++;echo 'PASS '.$label."\n";}
$user=wp_create_user('native_fixture',bin2hex(random_bytes(24)),'native-fixture@example.test');
$other=wp_create_user('other_fixture',bin2hex(random_bytes(24)),'other-fixture@example.test');
$admin=get_user_by('login','fixture_admin');
update_option('orbit_identity_origin','https://identity.example.test');
update_user_meta($user,'orbit_identity_identifier','native_fixture');
$avatar=get_avatar_data($user,array('size'=>2000));
verify_runtime(str_contains($avatar['url'],'/avatar/native_fixture?size=1024')&&$avatar['found_avatar'],'WordPress native user avatar uses bounded size and explicit binding');
$comment=new WP_Comment((object)array('comment_ID'=>0,'user_id'=>$user));
verify_runtime(str_contains(get_avatar_data($comment)['url'],'native_fixture'),'Real WordPress comment avatar resolves the bound user');
$post=new WP_Post((object)array('ID'=>0,'post_author'=>$user));
verify_runtime(str_contains(get_avatar_data($post)['url'],'native_fixture'),'Real WordPress author avatar resolves the bound user');
verify_runtime(str_contains(get_avatar_data('native-fixture@example.test')['url'],'native_fixture'),'Email input is resolved locally without transmitting its hash');
$fallback=get_avatar_data('unbound-sensitive@example.test');
verify_runtime(str_contains($fallback['url'],'fallback.svg')&&!str_contains($fallback['url'],'gravatar.com'),'Unbound user receives the local non-tracking fallback');
wp_set_current_user($other);
$denied=new WP_REST_Request('POST','/orbit-identity/v1/users/'.$user.'/binding');$denied->set_param('identifier','hijacked_fixture');
$response=rest_do_request($denied);
verify_runtime($response->get_status()===403&&get_user_meta($user,'orbit_identity_identifier',true)==='native_fixture','WordPress REST binding rejects another user');
wp_set_current_user($admin->ID);
$request=new WP_REST_Request('POST','/orbit-identity/v1/users/'.$user.'/binding');$request->set_param('identifier','updated_fixture');
verify_runtime(rest_do_request($request)->get_status()===200&&get_user_meta($user,'orbit_identity_identifier',true)==='updated_fixture','WordPress REST binding allows the current administrator');
$request->set_param('identifier','https://malicious.example');
verify_runtime(rest_do_request($request)->get_status()===400,'WordPress REST binding rejects non-native identifiers');
$_POST=array('orbit_identity_nonce'=>'invalid','orbit_identity_identifier'=>'hijacked_fixture');orbit_identity_save_profile($user);
verify_runtime(get_user_meta($user,'orbit_identity_identifier',true)==='updated_fixture','Profile settings reject an invalid WordPress nonce');
$_POST['orbit_identity_nonce']=wp_create_nonce('orbit_identity_profile');$_POST['orbit_identity_identifier']='native_fixture';orbit_identity_save_profile($user);
verify_runtime(get_user_meta($user,'orbit_identity_identifier',true)==='native_fixture','Profile settings accept the exact current WordPress nonce');
verify_runtime(WP_Block_Type_Registry::get_instance()->is_registered('orbit-identity/profile'),'Gutenberg block is registered with the real WordPress registry');
verify_runtime(has_filter('bp_core_fetch_avatar_url')!==false,'BuddyPress extension hook is registered');
$received=null;
$transport=function($pre,$args,$url)use(&$received){if(!str_starts_with($url,'https://identity.example.test/api/v1/profiles/'))return $pre;$received=$args;return array('response'=>array('code'=>200),'headers'=>array(),'body'=>wp_json_encode(array('id'=>'idn_'.str_repeat('a',32),'handle'=>'native_fixture','displayName'=>'<script>alert(1)</script>')),'cookies'=>array());};
add_filter('pre_http_request',$transport,10,3);
$card=orbit_identity_render_card(array('identifier'=>'native_fixture'));
verify_runtime(str_contains($card,'&lt;script&gt;')&&!str_contains($card,'<script>'),'Author card escapes public profile content using WordPress escaping');
verify_runtime($received['redirection']===0&&$received['timeout']===5&&$received['limit_response_size']===2097152,'WordPress HTTP request forbids redirects and bounds time and response size');
$read=new WP_REST_Request('GET','/orbit-identity/v1/profile/native_fixture');$response=rest_do_request($read);
verify_runtime($response->get_status()===200&&$response->get_headers()['Cache-Control']==='no-store','Public profile REST response preserves no-store privacy');
remove_filter('pre_http_request',$transport,10);
$private=wp_safe_remote_get('https://127.0.0.1/profile',array('timeout'=>1));
verify_runtime(is_wp_error($private),'Actual WordPress safe HTTP transport denies a private network target');
echo 'WordPress '.$GLOBALS['wp_version'].' runtime passed '.$checks." checks.\n";
file_put_contents(getenv('ORBIT_WP_REPORT'),wp_json_encode(array('version'=>$GLOBALS['wp_version'],'checks'=>$checks,'passed'=>true,'scope'=>'Real WordPress core, MariaDB, filters, REST permissions, nonce validation and block registration; remote profile projection mocked only for escaping and HTTP configuration assertions.'),JSON_PRETTY_PRINT)."\n");
